name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: SSH and deploy to EC2
  run: |
    ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o LogLevel=ERROR ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      cd /home/ec2-user/agentic-picks-backend
      git fetch origin main
      git reset --hard origin/main
      npm install
      pm2 restart backend || pm2 start index.js --name backend
    EOF
